name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy site
        run: npx eleventy

      - name: Add SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 5.78.141.123 >> ~/.ssh/known_hosts

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 5.78.141.123
          username: yk
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rsync -avz ./public/ /home/yk/web/yeldar.org/public_html/