name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy site
        run: npx eleventy

      - name: Save SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy via rsync
        run: |
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./public/ yk@5.78.141.123:/home/yk/web/yeldar.org/public_html/
      - name: Clean up
        run: rm -f private_key