name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy site
        run: npx eleventy

      - name: Copy site to remote server via SCP
        uses: appleboy/scp-action@master
        with:
          host: 5.78.141.123
          username: yk
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/*"
          target: "/home/yk/web/yeldar.org/public_html"
          rm: true
      - name: Done!
        run: echo "Deployed successfully!"